run-name: "Deploy Release"
name: "Deploy Release"
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    environment: Release
    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Extract version from commit message (Example logic, adjust as needed)
        id: extract_version
        run: echo "VERSION=v$(cat src/yapitest/__init__.py  | grep -o '[0-9]*\.[0-9]*\.[0-9]*')" >> $GITHUB_OUTPUT

      - name: Create Release
        if: steps.extract_version.outputs.VERSION != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.extract_version.outputs.VERSION }}
          release_name: Release ${{ steps.extract_version.outputs.VERSION }}
          body: |
            New Yapitest Releasej

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          # Optional: Caches dependencies for faster subsequent runs
          cache: 'pip'
      - name: Install Flit & Publish
        env:
          FLIT_USERNAME: ${{ secrets.FLIT_USERNAME }}
          FLIT_PASSWORD: ${{ secrets.FLIT_PASSWORD }}
        run: |
          python -m pip install flit
          python -m flit publish


